### ISSUE TITLE
ReplyError: ERR unknown command `FT.CREATE`

### ISSUE THREAD

**Issue by alexstaroselsky** [redis/redis-om-node#32]
Getting the following error when trying to create an index for using search/count functionality:

```txt
ReplyError: ERR unknown command `FT.CREATE`, with args beginning with: `Album:index`, `ON`, `JSON`, `PREFIX`, `1`, `Album:`, `SCHEMA`, `$.artist`, `AS`, `artist`, `TAG`, `SEPARATOR`, `|`, `$.title`
```

 When trying to `await repository.createIndex()` with the following code. `Client` is able to `open`/connect as responds to `['PING']`. Trying to see if missing anything obvious with creating a repository and creating an index with json and search module enabled.

docker-compose.yml (copied from https://github.com/redis/redis-om-node/blob/main/docker/docker-compose.yml):

```yml
version: '3.9'
services:
  redis:
    image: 'redislabs/redismod:preview'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisai.so
          ONNX redisai_onnxruntime/redisai_onnxruntime.so
          TF redisai_tensorflow/redisai_tensorflow.so
          TFLITE redisai_tflite/redisai_tflite.so
          TORCH redisai_torch/redisai_torch.so   
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/redisgraph.so
        --loadmodule /usr/lib/redis/modules/redistimeseries.so
        --loadmodule /usr/lib/redis/modules/rejson.so
        --loadmodule /usr/lib/redis/modules/redisbloom.so
        --loadmodule /usr/lib/redis/modules/redisgears.so
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```

module:
```js
const { Client, Entity, Repository, Schema } = require('redis-om');

class Album extends Entity {}

const schema = new Schema(
  Album,
  {
    artist: { type: 'string' },
    title: { type: 'string' },
    year: { type: 'number' },
    genres: { type: 'array' },
    outOfPublication: { type: 'boolean' },
  },
  {
    dataStructure: 'JSON',
  },
);

(async function() {
  const client = new Client();
  await client.open();
  console.log(await client.execute(['PING'])); // PONG
  const repository = new Repository(schema, client);
  await repository.createIndex();
})();

```
