### ISSUE TITLE
Find all not working

### ISSUE THREAD

**Issue by kamalkech** [redis/redis-om-node#63]
```typescript
const client = new Client();
await client.open('redis://localhost:6379');

let tokenAPiRepository = client.fetchRepository(tokenSchema);
return await tokenAPiRepository.search().return.all();
```

 i get this error:
 ```ERR unknown command `FT.SEARCH`, with args beginning with: `TokenApi:index`, `*`, `LIMIT`, `0`, `10`,```
 
 any idea to fixe that ?

**Comment by guyroyse** [comment]
This is most likely the result of not having a version of Redis with RediSearch installed. What version of Redis are you running? Where is it running?

**Comment by kamalkech** [comment]
@guyroyse 
```
"redis": "^4.0.6",
"redis-om": "^0.2.1"
```

**Comment by guyroyse** [comment]
What version of Redis Server are you running? Where is it running?

**Comment by kamalkech** [comment]
@guyroyse it s from current https://hub.docker.com/_/redis

**Comment by guyroyse** [comment]
That's the vanilla version of Redis. You need to run Redis Stack or another flavor of Redis that has RediSearch installed. Details on how to get it are here: https://redis.io/docs/stack/. Docker is an option.

**Comment by kamalkech** [comment]
@guyroyse for docker + redisstack i found this https://redis.io/docs/stack/get-started/install/docker/
and thank u for answers

**Comment by humblecoder** [comment]
Hrm, I'm definitely using RedisStack:

```
services:
  redisdocker:
    image: redis/redis-stack-server:latest
    restart: "unless-stopped"
    ports:
      - 6379:6379
    volumes:
      - "./apps/backend/storage-redis/data:/data"

  redisinsights:
    image: redislabs/redisinsight:latest
    restart: "unless-stopped"
    ports:
      - '8001:8001'
    volumes:
      - "./apps/backend/storage-redis/redisinsight:/db"
```

. . . but I'm having the same issue.  When I scan "myRepository:*" via RedisInsight, I have a few hundred items, but when I query via redis-om, less than 100 show up.  I did **dramatically** adjust the "schema" in the last few days, but I only added to.   Could re-indexing cause this?  🤔
